# Generated by Django 2.1.7 on 2019-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='like_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_list',
            field=models.TextField(blank=True),
        ),
    ]
