# Generated by Django 2.1.7 on 2019-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_tag_post_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
