# Generated by Django 2.1.7 on 2019-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_tag_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
