# Generated by Django 2.1.7 on 2019-03-21 09:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_category_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinaccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='coinaccount',
            name='deposit',
        ),
        migrations.AddField(
            model_name='coinaccount',
            name='block',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
