# Generated by Django 2.1.7 on 2019-03-21 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20190321_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinaccount',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
